image:
  repository: microsoft/virtual-kubelet
  tag: latest
  pullPolicy: Always
env:
  azureClientId: 
  azureClientKey: 
  azureTenantId: 
  azureSubscriptionId: 
  aciResourceGroup: 
  aciRegion: 
  nodeName: 
  nodeTaint: 
  nodeOsType: 
  apiserverCert: 
  apiserverKey: 
  monitoredNamespace:
  aciVnetSubnetName:
  aciVnetSubnetCidr:
  masterUri:
  clusterCidr:
  kubeDnsIp:
loganalytics:
  enabled: false
  workspaceID:
  workspaceKey:

# Install Default RBAC roles and bindings
rbac:
  install: true
  ## RBAC api version
  apiVersion: v1beta1
  # Cluster role reference
  roleRef: cluster-admin