apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: virtual-kubelet
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: virtual-kubelet
    spec:
      containers:
      - name: virtual-kubelet
        image: rbitia/virtual-kubelet:latest
        imagePullPolicy: Always
        env:
        - name: AZURE_CLIENT_ID
          value: $clientId
        - name: AZURE_CLIENT_KEY
          value: $clientSecret
        - name: AZURE_TENANT_ID
          value: $tenantId
        - name: AZURE_SUBSCRIPTION_ID
          value: $subscriptionId
        - name: ACI_RESOURCE_GROUP
          value: $aciRecourceGroup
